version: "3.3"

services:
    server:
        build: server/.
        ports:
            - "3001:3001"
    
    client:
        build: client/.
        links:
            - server
        depends_on:
            - server
        ports:
          - "3000:3000"